export const produits = [
  {
    id: 1,
    produitNom: "Choco Cerise",
    prix: 5.0,
    produitImage: "/images/produit1.jpg",
    categorie: ["Chocolat au lait", "Noix/Noisette", "Fruit"],
    rating: 2.5,
  },
  {
    id: 2,
    produitNom: "Choco Caramel",
    prix: 5.5,
    produitImage: "/images/produit2.jpg",
    categorie: ["Chocolat au lait", "Caramel"],
    rating: 2.5,
  },
  {
    id: 3,
    produitNom: "Choco Confiture",
    prix: 6.0,
    produitImage: "/images/produit3.jpg",
    categorie: ["Chocolat au lait", "Fruit", "Liqueur"],
    rating: 3,
  },
  {
    id: 4,
    produitNom: "Choco Coeur",
    prix: 6.5,
    produitImage: "/images/produit4.jpg",
    categorie: ["Chocolat blanc", "Liqueur"],
    rating: 3,
  },
  {
    id: 5,
    produitNom: "Choco Noisette",
    prix: 7.0,
    produitImage: "/images/produit5.jpg",
    categorie: ["Chocolat au lait", "Noix/Noisette"],
    rating: 3.5,
  },
  {
    id: 6,
    produitNom: "Choco Blanc",
    prix: 7.5,
    produitImage: "/images/produit6.jpg",
    categorie: ["Chocolat blanc", "Chocolat noir"],
    rating: 3.5,
  },
  {
    id: 7,
    produitNom: "Choco Fraise",
    prix: 8.5,
    produitImage: "/images/produit7.jpg",
    categorie: ["Chocolat au lait", "Noix/Noisette", "Fruit", "Liqueur"],
    rating: 4.5,
  },
  {
    id: 8,
    produitNom: "Choco Love",
    prix: 8.0,
    produitImage: "/images/produit8.jpg",
    categorie: ["Chocolat noir"],
    rating: 4,
  },
  {
    id: 9,
    produitNom: "Choco Pepite",
    prix: 9.0,
    produitImage: "/images/produit9.jpg",
    categorie: ["Chocolat au lait", "Caramel"],
    rating: 5,
  },
  {
    id: 10,
    produitNom: "Choco Bonbon",
    prix: 10.0,
    produitImage: "/images/produit10.jpg",
    categorie: ["Chocolat noir", "Noix/Noisette", "Caramel"],
    rating: 5,
  },
];
